[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "pymmunomics"
version = "1.0.0"
description = "Package containing adaptive immune receptor analysis methods"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
  {name = "Jasper Braun", email = "jasperbraun90@gmail.com"},
]
keywords = ["AIRR", "immunology", "immune repertoire"]
dependencies = [ "numpy==2.1.2", "openpyxl==3.1.5", "pandas==2.2.3", "polyleven==0.8", "ray>=2.4.0", "scikit-learn>=1.2.2", "scikit-optimize>=0.9.0", "scipy>=1.10.1" ]

[project.urls]
repository = "https://github.com/JasperBraun/pymmunomics.git"

[project.optional-dependencies]
dev = [
  "numpydoc>=1.5.0",
  "pytest>=7.3.1",
  "pytest-cov>=4.1.0",
  "sphinx>=7.0.1",
]

[tool.pytest.ini_options]
addopts = "--cov --cov-report html --cov-report term-missing --cov-fail-under 95"

[tool.coverage.run]
source = ["src"]
